name: "Build"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: install xorg-dev on ubuntu
      run: ./install_xorg_dev.sh

    - name: Build and install
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
